### ISSUE TITLE
result slightly differents

### ISSUE THREAD

**Issue by jpainam** [QizeYang/PAUL#18]
Hi, thank you for sharing your code. it works perfectly, I have a little concern. On Market-1501 dataset, i got the following results;
```python
Mean AP: 39.78% # instead of 40.1+
CMC Scores first_match
  top-1         67.96%  # instead of 68.5+
  top-5         81.53% # instead of 82.4+
  top-10        86.97% # instead of 87.4
  top-15        89.43%
  top-20        90.83%

```
which are a little lower than the reported results.
This is the command i used to run the unsupervised method.
Is there a specific parameters am missing to get your results?
Thank you.

**Comment by faize5** [comment]
Hi Jpainam, which command you have used to test the model after training on Market-1501 dataset. Please share the command or procedure in detail. I'm waiting for your kind response. 
Thank you
