### ISSUE TITLE
How many GPUs are needed?

### ISSUE THREAD

**Issue by XiumeiChen** [QizeYang/PAUL#2]
Thank you for sharing.
I trained the unsupervised model on a GeForce GPU of 12G , and I got a OUT OF MEMORY cuda error. So could you detail the usage of GPUs？Or there are other mistakes I have ignored?
![image](https://user-images.githubusercontent.com/44281274/61167820-8ce43200-a576-11e9-80a9-d9d520005fd5.png)
![image](https://user-images.githubusercontent.com/44281274/61167826-a1c0c580-a576-11e9-8411-a29a8a85438e.png)

**Comment by QizeYang** [comment]
Hi, these experiments require 2 GPUs (1080ti or Titan X) at least. Thank you.
