### ISSUE TITLE
About centers initialization

### ISSUE THREAD

**Issue by ggalan87** [QizeYang/PAUL#3]
Is there a reason why you initialize patch_centers but not centers before the unsupervised training below https://github.com/QizeYang/PAUL/blob/28cb0764c5827d5bbc3cca48a0728b94855afe6d/src/unsupervised/unsupervised_train.py#L155-L167

Furthermore, is there any reason for initialization beforehand? As I understand such initialization is achieved during first epoch.

**Comment by QizeYang** [comment]
Because we need to compute the pair-wise distances between all patches in the dataset, we need to initialize all the patch centers before computing the PEDAL. As for the center of the whole images, we only compute the IPFL within the current batch, so we don't need to initialize it first.
