### ISSUE TITLE
data preparation

### ISSUE THREAD

**Issue by 2110317008** [QizeYang/PAUL#4]
root@6e5c9e14f90a:/home/PAUL-master/src/data# ln -s [PATH TO MSMT17_V1] ./data/MSMT17_V1
ln: target './data/MSMT17_V1' is not a directory
root@6e5c9e14f90a:/home/PAUL-master/src/data#
How can I solve this problem?Thank you!

**Comment by QizeYang** [comment]
Emmm, have you specified the path of MSMT17_V1? For example, `ln -s /home/share/data/MSMT17_V1 ./data/MSMT17_V1`
